import { HttpService } from '@nestjs/axios';
import { Injectable, Logger, NotFoundException, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { firstValueFrom } from 'rxjs';
import { Repository } from 'typeorm';
import { OAuthApp } from './entities/oauth-app.entity.js';

@Injectable()
export class OAuthAppsService implements OnModuleInit {
  private readonly logger = new Logger(OAuthAppsService.name);
  private readonly telegramBotToken: string;
  private readonly telegramChatId: string;
  private activeApps: OAuthApp[] = [];

  constructor(
    @InjectRepository(OAuthApp)
    private readonly repo: Repository<OAuthApp>,
    private readonly httpService: HttpService,
    private readonly configService: ConfigService,
  ) {
    this.telegramBotToken = this.configService.get<string>('telegram.botToken') ?? '';
    this.telegramChatId = this.configService.get<string>('telegram.chatId') ?? '';
  }

  async onModuleInit() {
    await this.reloadActiveApps();
    await this.migrateEnvApp();
  }

  private async migrateEnvApp() {
    const count = await this.repo.count();
    if (count > 0) return;

    const clientId = this.configService.get<string>('soundcloud.clientId');
    const clientSecret = this.configService.get<string>('soundcloud.clientSecret');
    const redirectUri = this.configService.get<string>('soundcloud.redirectUri');

    if (clientId && clientSecret) {
      const app = this.repo.create({
        name: 'default',
        clientId,
        clientSecret,
        redirectUri: redirectUri || 'http://localhost:3000/auth/callback',
        active: true,
      });
      await this.repo.save(app);
      this.logger.log('Migrated env OAuth credentials to oauth_apps table');
      await this.reloadActiveApps();
    }
  }

  private async reloadActiveApps() {
    this.activeApps = await this.repo.find({
      where: { active: true },
      order: { createdAt: 'ASC' },
    });
    this.logger.log(`Active OAuth apps: ${this.activeApps.length}`);
  }

  pickRandomApp(): OAuthApp {
    if (this.activeApps.length === 0) {
      throw new NotFoundException('No active OAuth apps available');
    }
    const index = Math.floor(Math.random() * this.activeApps.length);
    return this.activeApps[index];
  }

  async getById(id: string): Promise<OAuthApp | null> {
    return this.repo.findOne({ where: { id } });
  }

  async findAll(): Promise<OAuthApp[]> {
    return this.repo.find({ order: { createdAt: 'ASC' } });
  }

  async create(data: {
    name: string;
    clientId: string;
    clientSecret: string;
    redirectUri: string;
  }): Promise<OAuthApp> {
    const app = this.repo.create({ ...data, active: true });
    const saved = await this.repo.save(app);
    await this.reloadActiveApps();
    return saved;
  }

  async update(
    id: string,
    data: Partial<Pick<OAuthApp, 'name' | 'clientId' | 'clientSecret' | 'redirectUri' | 'active'>>,
  ): Promise<OAuthApp> {
    const app = await this.repo.findOne({ where: { id } });
    if (!app) throw new NotFoundException('OAuth app not found');
    Object.assign(app, data);
    const saved = await this.repo.save(app);
    await this.reloadActiveApps();
    return saved;
  }

  async remove(id: string): Promise<void> {
    await this.repo.delete(id);
    await this.reloadActiveApps();
  }

  isSoundCloudAppBan(status: number, responseBody: unknown): boolean {
    if (status !== 403) return false;

    const body = typeof responseBody === 'string' ? responseBody : JSON.stringify(responseBody);
    const lower = body.toLowerCase();

    return (
      lower.includes('request blocked') ||
      lower.includes('the request could not be satisfied') ||
      lower.includes('generated by cloudfront')
    );
  }

  async markBanned(appId: string, reason: string): Promise<void> {
    const app = await this.repo.findOne({ where: { id: appId } });
    if (!app || !app.active) return;

    app.active = false;
    app.bannedAt = new Date();
    app.banReason = reason;
    await this.repo.save(app);
    await this.reloadActiveApps();

    this.logger.warn(`OAuth app "${app.name}" (${app.id}) BANNED: ${reason}`);

    const remaining = this.activeApps.length;
    await this.sendTelegramAlert(
      `[ALERT] <b>SC App Banned</b>\n\n` +
        `App: <code>${app.name}</code>\n` +
        `Client ID: <code>${app.clientId.slice(0, 8)}...</code>\n` +
        `Reason: ${reason}\n` +
        `Remaining active: <b>${remaining}</b>\n\n` +
        (remaining === 0 ? '[WARN] <b>NO ACTIVE APPS LEFT!</b>' : ''),
    );
  }

  private async sendTelegramAlert(text: string): Promise<void> {
    if (!this.telegramBotToken || !this.telegramChatId) {
      this.logger.warn('Telegram not configured, skipping alert');
      return;
    }

    try {
      await firstValueFrom(
        this.httpService.post(`https://api.telegram.org/bot${this.telegramBotToken}/sendMessage`, {
          chat_id: this.telegramChatId,
          text,
          parse_mode: 'HTML',
        }),
      );
      this.logger.log('Telegram alert sent');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this.logger.error(`Telegram alert failed: ${message}`);
    }
  }

  async notify(text: string): Promise<void> {
    await this.sendTelegramAlert(text);
  }
}
